from celery.backends.base import BaseBackend
from typing import Any, Optional

class DatabaseBackend(BaseBackend):
    subpolling_interval: float = ...
    task_cls: Any = ...
    taskset_cls: Any = ...
    url: Any = ...
    engine_options: Any = ...
    short_lived_sessions: Any = ...
    def __init__(self, dburi: Optional[Any] = ..., engine_options: Optional[Any] = ..., url: Optional[Any] = ..., **kwargs: Any) -> None: ...
    @property
    def extended_result(self): ...
    def ResultSession(self, session_manager: Any = ...): ...
    def cleanup(self) -> None: ...
    def __reduce__(self, args: Any = ..., kwargs: Optional[Any] = ...): ...
