from typing import Any

class SessionManager:
    forked: bool = ...
    prepared: bool = ...
    def __init__(self) -> None: ...
    def get_engine(self, dburi: Any, **kwargs: Any): ...
    def create_session(self, dburi: Any, short_lived_sessions: bool = ..., **kwargs: Any): ...
    def prepare_models(self, engine: Any) -> None: ...
    def session_factory(self, dburi: Any, **kwargs: Any): ...
