from typing import Any, Optional

def TaskMessage(name: Any, id: Optional[Any] = ..., args: Any = ..., kwargs: Optional[Any] = ..., callbacks: Optional[Any] = ..., errbacks: Optional[Any] = ..., chain: Optional[Any] = ..., shadow: Optional[Any] = ..., utc: Optional[Any] = ..., **options: Any): ...
def TaskMessage1(name: Any, id: Optional[Any] = ..., args: Any = ..., kwargs: Optional[Any] = ..., callbacks: Optional[Any] = ..., errbacks: Optional[Any] = ..., chain: Optional[Any] = ..., **options: Any): ...
def task_message_from_sig(app: Celery, sig: Signature, utc: bool=..., TaskMessage: Any=...) -> Any: ...
