from typing import Any, Optional

event_exchange: Any

def Event(type: Any, _fields: Optional[Any] = ..., __dict__: Any = ..., __now__: Any = ..., **fields: Any): ...
def group_from(type: Any): ...
def get_exchange(conn: Any, name: Any = ...): ...
