from typing import Any, Optional

class Polaroid:
    timer: Any = ...
    shutter_signal: Any = ...
    cleanup_signal: Any = ...
    clear_after: bool = ...
    app: Any = ...
    state: Any = ...
    freq: Any = ...
    cleanup_freq: Any = ...
    logger: Any = ...
    maxrate: Any = ...
    def __init__(self, state: Any, freq: float = ..., maxrate: Optional[Any] = ..., cleanup_freq: float = ..., timer: Optional[Any] = ..., app: Optional[Any] = ...) -> None: ...
    def install(self) -> None: ...
    def on_shutter(self, state: Any) -> None: ...
    def on_cleanup(self) -> None: ...
    def cleanup(self) -> None: ...
    def shutter(self) -> None: ...
    def capture(self) -> None: ...
    def cancel(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *exc_info: Any) -> None: ...

def evcam(camera: Any, freq: float = ..., maxrate: Optional[Any] = ..., loglevel: int = ..., logfile: Optional[Any] = ..., pidfile: Optional[Any] = ..., timer: Optional[Any] = ..., app: Optional[Any] = ...) -> None: ...
