from celery.utils import deprecated as deprecated
from typing import Any, Optional

def get_backend_cls(backend: Optional[Any] = ..., loader: Optional[Any] = ..., **kwargs: Any): ...
def get_backend_by_url(backend: Optional[Any] = ..., loader: Optional[Any] = ...): ...
