from .base import KeyValueStoreBackend
from typing import Any, Optional

class ArangoDbBackend(KeyValueStoreBackend):
    host: str = ...
    port: str = ...
    database: str = ...
    collection: str = ...
    username: Any = ...
    password: Any = ...
    http_protocol: str = ...
    key_t: Any = ...
    url: Any = ...
    arangodb_url: Any = ...
    def __init__(self, url: Optional[Any] = ..., *args: Any, **kwargs: Any) -> None: ...
    @property
    def connection(self): ...
    @property
    def db(self): ...
    def get(self, key: Any): ...
    def set(self, key: Any, value: Any) -> None: ...
    def mget(self, keys: Any): ...
    def delete(self, key: Any) -> None: ...
