from .base import KeyValueStoreBackend
from typing import Any, Optional

class AzureBlockBlobBackend(KeyValueStoreBackend):
    def __init__(self, url: Optional[Any] = ..., container_name: Optional[Any] = ..., retry_initial_backoff_sec: Optional[Any] = ..., retry_increment_base: Optional[Any] = ..., retry_max_attempts: Optional[Any] = ..., *args: Any, **kwargs: Any) -> None: ...
    def get(self, key: Any): ...
    def set(self, key: Any, value: Any): ...
    def mget(self, keys: Any): ...
    def delete(self, key: Any) -> None: ...
