from .base import BaseBackend
from typing import Any, Optional

class CassandraBackend(BaseBackend):
    servers: Any = ...
    supports_autoexpire: bool = ...
    port: Any = ...
    keyspace: Any = ...
    table: Any = ...
    cassandra_options: Any = ...
    cqlexpires: Any = ...
    read_consistency: Any = ...
    write_consistency: Any = ...
    auth_provider: Any = ...
    def __init__(self, servers: Optional[Any] = ..., keyspace: Optional[Any] = ..., table: Optional[Any] = ..., entry_ttl: Optional[Any] = ..., port: int = ..., **kwargs: Any) -> None: ...
    def process_cleanup(self) -> None: ...
    def as_uri(self, include_password: bool = ...): ...
    def __reduce__(self, args: Any = ..., kwargs: Optional[Any] = ...): ...
