from celery.backends.base import KeyValueStoreBackend
from typing import Any

class ConsulBackend(KeyValueStoreBackend):
    consul: Any = ...
    supports_autoexpire: bool = ...
    client: Any = ...
    consistency: str = ...
    path: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get(self, key: Any): ...
    def mget(self, keys: Any) -> None: ...
    def set(self, key: Any, value: Any): ...
    def delete(self, key: Any): ...
