from .base import KeyValueStoreBackend
from typing import Any, Optional

class CosmosDBSQLBackend(KeyValueStoreBackend):
    def __init__(self, url: Optional[Any] = ..., database_name: Optional[Any] = ..., collection_name: Optional[Any] = ..., consistency_level: Optional[Any] = ..., max_retry_attempts: Optional[Any] = ..., max_retry_wait_time: Optional[Any] = ..., *args: Any, **kwargs: Any) -> None: ...
    def get(self, key: Any): ...
    def set(self, key: Any, value: Any) -> None: ...
    def mget(self, keys: Any): ...
    def delete(self, key: Any) -> None: ...
