from .base import KeyValueStoreBackend
from typing import Any, Optional

class CouchbaseBackend(KeyValueStoreBackend):
    bucket: str = ...
    host: str = ...
    port: int = ...
    username: Any = ...
    password: Any = ...
    quiet: bool = ...
    supports_autoexpire: bool = ...
    timeout: float = ...
    key_t: Any = ...
    url: Any = ...
    def __init__(self, url: Optional[Any] = ..., *args: Any, **kwargs: Any) -> None: ...
    @property
    def connection(self): ...
    def get(self, key: Any): ...
    def set(self, key: Any, value: Any) -> None: ...
    def mget(self, keys: Any): ...
    def delete(self, key: Any) -> None: ...
