from .base import KeyValueStoreBackend
from typing import Any, Optional

class ElasticsearchBackend(KeyValueStoreBackend):
    index: str = ...
    doc_type: str = ...
    scheme: str = ...
    host: str = ...
    port: int = ...
    username: Any = ...
    password: Any = ...
    es_retry_on_timeout: bool = ...
    es_timeout: int = ...
    es_max_retries: int = ...
    url: Any = ...
    def __init__(self, url: Optional[Any] = ..., *args: Any, **kwargs: Any) -> None: ...
    def get(self, key: Any): ...
    def set(self, key: Any, value: Any) -> None: ...
    def mget(self, keys: Any): ...
    def delete(self, key: Any) -> None: ...
    @property
    def server(self): ...
