from celery import uuid as uuid
from celery.backends.base import KeyValueStoreBackend as KeyValueStoreBackend
from celery.exceptions import ImproperlyConfigured as ImproperlyConfigured
from typing import Any, Optional

FileNotFoundError = IOError
IsADirectoryError = IOError
default_encoding: Any
E_NO_PATH_SET: str
E_PATH_NON_CONFORMING_SCHEME: str
E_PATH_INVALID: str

class FilesystemBackend(KeyValueStoreBackend):
    url: Any = ...
    path: Any = ...
    sep: Any = ...
    open: Any = ...
    unlink: Any = ...
    def __init__(self, url: Optional[Any] = ..., open: Any = ..., unlink: Any = ..., sep: Any = ..., encoding: Any = ..., *args: Any, **kwargs: Any) -> None: ...
    def get(self, key: Any): ...
    def set(self, key: Any, value: Any) -> None: ...
    def mget(self, keys: Any) -> None: ...
    def delete(self, key: Any) -> None: ...
