from .base import KeyValueStoreBackend
from typing import Any, Optional

class RiakBackend(KeyValueStoreBackend):
    protocol: str = ...
    bucket_name: str = ...
    host: str = ...
    port: int = ...
    url: Any = ...
    def __init__(self, host: Optional[Any] = ..., port: Optional[Any] = ..., bucket_name: Optional[Any] = ..., protocol: Optional[Any] = ..., url: Optional[Any] = ..., *args: Any, **kwargs: Any) -> None: ...
    @property
    def client(self): ...
    @property
    def bucket(self): ...
    def get(self, key: Any): ...
    def set(self, key: Any, value: Any) -> None: ...
    def mget(self, keys: Any): ...
    def delete(self, key: Any) -> None: ...
