from typing import Any, Optional

class Beat:
    Service: Any = ...
    app: Any = ...
    loglevel: Any = ...
    logfile: Any = ...
    schedule: Any = ...
    scheduler_cls: Any = ...
    redirect_stdouts: Any = ...
    redirect_stdouts_level: Any = ...
    max_interval: Any = ...
    socket_timeout: Any = ...
    no_color: Any = ...
    colored: Any = ...
    pidfile: Any = ...
    def __init__(self, max_interval: Optional[Any] = ..., app: Optional[Any] = ..., socket_timeout: int = ..., pidfile: Optional[Any] = ..., no_color: Optional[Any] = ..., loglevel: str = ..., logfile: Optional[Any] = ..., schedule: Optional[Any] = ..., scheduler: Optional[Any] = ..., scheduler_cls: Optional[Any] = ..., redirect_stdouts: Optional[Any] = ..., redirect_stdouts_level: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def run(self) -> None: ...
    def setup_logging(self, colorize: Optional[Any] = ...) -> None: ...
    def start_scheduler(self) -> None: ...
    def banner(self, service: Any): ...
    def init_loader(self) -> None: ...
    def startup_info(self, service: Any): ...
    def set_process_title(self) -> None: ...
    def install_sync_handler(self, service: Any) -> None: ...
