from typing import Any

class Certificate:
    def __init__(self, cert: Any) -> None: ...
    def has_expired(self): ...
    def get_pubkey(self): ...
    def get_serial_number(self): ...
    def get_issuer(self): ...
    def get_id(self): ...
    def verify(self, data: Any, signature: Any, digest: Any) -> None: ...

class CertStore:
    def __init__(self) -> None: ...
    def itercerts(self) -> None: ...
    def __getitem__(self, id: Any): ...
    def add_cert(self, cert: Any) -> None: ...

class FSCertStore(CertStore):
    def __init__(self, path: Any) -> None: ...
