from celery import Task
from celery.result import AsyncResult
from typing import Any

class AbortableAsyncResult(AsyncResult):
    def is_aborted(self): ...
    def abort(self): ...

class AbortableTask(Task):
    abstract: bool = ...
    def AsyncResult(self, task_id: Any): ...
    def is_aborted(self, **kwargs: Any): ...
