from pdb import Pdb
from typing import Any, Optional

DEFAULT_PORT: int
CELERY_RDB_HOST: Any
CELERY_RDB_PORT: Any

class Rdb(Pdb):
    me: str = ...
    active: bool = ...
    out: Any = ...
    ident: Any = ...
    host: Any = ...
    port: Any = ...
    remote_addr: Any = ...
    def __init__(self, host: Any = ..., port: Any = ..., port_search_limit: int = ..., port_skew: int = ..., out: Any = ...) -> None: ...
    def get_avail_port(self, host: Any, port: Any, search_limit: int = ..., skew: int = ...): ...
    def say(self, m: Any) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *exc_info: Any) -> None: ...
    def do_continue(self, arg: Any): ...
    do_c: Any = ...
    do_cont: Any = ...
    def do_quit(self, arg: Any): ...
    do_q: Any = ...
    do_exit: Any = ...
    def set_quit(self) -> None: ...

def debugger(): ...
def set_trace(frame: Optional[Any] = ...): ...
