from kombu.utils.imports import symbol_by_name as symbol_by_name
from typing import Any, Optional

class NotAPackage(Exception): ...

def qualname(obj: Any): ...
def instantiate(name: Any, *args: Any, **kwargs: Any): ...
def cwd_in_path() -> None: ...
def find_module(module: Any, path: Optional[Any] = ..., imp: Optional[Any] = ...): ...
def import_from_cwd(module: Any, imp: Optional[Any] = ..., package: Optional[Any] = ...): ...
def reload_from_cwd(module: Any, reloader: Optional[Any] = ...): ...
def module_file(module: Any): ...
def gen_task_name(app: Any, name: Any, module_name: Any): ...
