from typing import Any, Optional

gethostname: Any

def worker_direct(hostname: Any): ...
def nodename(name: Any, hostname: Any): ...
def anon_nodename(hostname: Optional[Any] = ..., prefix: str = ...): ...
def nodesplit(name: Any): ...
def default_nodename(hostname: Any): ...
def node_format(s: Any, name: Any, **extra: Any): ...
def host_format(s: Any, host: Optional[Any] = ..., name: Optional[Any] = ..., **extra: Any): ...
