from typing import Any, Optional

class Bunch:
    def __init__(self, **kwargs: Any) -> None: ...

def mro_lookup(cls, attr: Any, stop: Optional[Any] = ..., monkey_patched: Optional[Any] = ...): ...

class FallbackContext:
    provided: Any = ...
    fallback: Any = ...
    fb_args: Any = ...
    fb_kwargs: Any = ...
    def __init__(self, provided: Any, fallback: Any, *fb_args: Any, **fb_kwargs: Any) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *exc_info: Any): ...

class getitem_property:
    path: Any = ...
    __doc__: Any = ...
    def __init__(self, keypath: Any, doc: Optional[Any] = ...) -> None: ...
    def __get__(self, obj: Any, type: Optional[Any] = ...): ...
    def __set__(self, obj: Any, value: Any) -> None: ...
