from typing import Any

def load_average(): ...

class df:
    path: Any = ...
    def __init__(self, path: Any) -> None: ...
    @property
    def total_blocks(self): ...
    @property
    def available(self): ...
    @property
    def capacity(self): ...
    def stat(self): ...
