from typing import Any

class colored:
    s: Any = ...
    enabled: Any = ...
    op: Any = ...
    names: Any = ...
    def __init__(self, *s: Any, **kwargs: Any) -> None: ...
    def no_color(self): ...
    def embed(self): ...
    def node(self, s: Any, op: Any): ...
    def black(self, *s: Any): ...
    def red(self, *s: Any): ...
    def green(self, *s: Any): ...
    def yellow(self, *s: Any): ...
    def blue(self, *s: Any): ...
    def magenta(self, *s: Any): ...
    def cyan(self, *s: Any): ...
    def white(self, *s: Any): ...
    def bold(self, *s: Any): ...
    def underline(self, *s: Any): ...
    def blink(self, *s: Any): ...
    def reverse(self, *s: Any): ...
    def bright(self, *s: Any): ...
    def ired(self, *s: Any): ...
    def igreen(self, *s: Any): ...
    def iyellow(self, *s: Any): ...
    def iblue(self, *s: Any): ...
    def imagenta(self, *s: Any): ...
    def icyan(self, *s: Any): ...
    def iwhite(self, *s: Any): ...
    def reset(self, *s: Any): ...
    def __add__(self, other: Any): ...
