from typing import Any, Optional

class Heart:
    timer: Any = ...
    eventer: Any = ...
    interval: Any = ...
    tref: Any = ...
    def __init__(self, timer: Any, eventer: Any, interval: Optional[Any] = ...) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
