from typing import Any

def asynloop(obj: Any, connection: Any, consumer: Any, blueprint: Any, hub: Any, qos: Any, heartbeat: Any, clock: Any, hbrate: float = ...) -> None: ...
def synloop(obj: Any, connection: Any, consumer: Any, blueprint: Any, hub: Any, qos: Any, heartbeat: Any, clock: Any, hbrate: float = ..., **kwargs: Any) -> None: ...
