from typing import Any

class Pidbox:
    consumer: Any = ...
    c: Any = ...
    hostname: Any = ...
    node: Any = ...
    def __init__(self, c: Any) -> None: ...
    def on_message(self, body: Any, message: Any) -> None: ...
    def start(self, c: Any) -> None: ...
    def on_stop(self) -> None: ...
    def stop(self, c: Any) -> None: ...
    def reset(self) -> None: ...
    def shutdown(self, c: Any) -> None: ...

class gPidbox(Pidbox):
    def start(self, c: Any) -> None: ...
    def on_stop(self) -> None: ...
    def reset(self) -> None: ...
    def loop(self, c: Any) -> None: ...
