from .base import BasePool
from typing import Any

class TaskPool(BasePool):
    body_can_be_buffer: bool = ...
    on_apply: Any = ...
    limit: int = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
