from typing import Any

class MapAnnotation(dict):
    def annotate_any(self): ...
    def annotate(self, task: Any): ...

def prepare(annotations: Any): ...
def resolve_all(anno: Any, task: Any): ...
