from typing import Any, Optional

def by_name(backend: Optional[Any] = ..., loader: Optional[Any] = ..., extension_namespace: str = ...): ...
def by_url(backend: Optional[Any] = ..., loader: Optional[Any] = ...): ...
