from celery._state import connect_on_app_finalize as connect_on_app_finalize
from celery.utils.log import get_logger as get_logger
from typing import Any

logger: Any

def add_backend_cleanup_task(app: Any): ...
def add_accumulate_task(app: Any): ...
def add_unlock_chord_task(app: Any): ...
def add_map_task(app: Any): ...
def add_starmap_task(app: Any): ...
def add_chunk_task(app: Any): ...
def add_group_task(app: Any): ...
def add_chain_task(app: Any): ...
def add_chord_task(app: Any): ...
