from collections import namedtuple
from typing import Any, Optional

searchresult = namedtuple('searchresult', ['namespace', 'key', 'type'])

class Option:
    alt: Any = ...
    deprecate_by: Any = ...
    remove_by: Any = ...
    old: Any = ...
    typemap: Any = ...
    default: Any = ...
    type: Any = ...
    def __init__(self, default: Optional[Any] = ..., *args: Any, **kwargs: Any) -> None: ...
    def to_python(self, value: Any): ...

NAMESPACES: Any

def flatten(d: Any, root: str = ..., keyfilter: Any = ...) -> None: ...
def find(name: Any, namespace: str = ...): ...
