from typing import Any

class TaskRegistry(dict):
    NotRegistered: Any = ...
    def __missing__(self, key: Any) -> None: ...
    def register(self, task: Any) -> None: ...
    def unregister(self, name: Any) -> None: ...
    def regular(self): ...
    def periodic(self): ...
    def filter_types(self, type: Any): ...
