from typing import Any, Optional

class MapRoute:
    map: Any = ...
    patterns: Any = ...
    def __init__(self, map: Any) -> None: ...
    def __call__(self, name: Any, *args: Any, **kwargs: Any): ...

class Router:
    app: Any = ...
    queues: Any = ...
    routes: Any = ...
    create_missing: Any = ...
    def __init__(self, routes: Optional[Any] = ..., queues: Optional[Any] = ..., create_missing: bool = ..., app: Optional[Any] = ...) -> None: ...
    def route(self, options: Any, name: Any, args: Any = ..., kwargs: Optional[Any] = ..., task_type: Optional[Any] = ...): ...
    def expand_destination(self, route: Any): ...
    def lookup_route(self, name: Any, args: Optional[Any] = ..., kwargs: Optional[Any] = ..., options: Optional[Any] = ..., task_type: Optional[Any] = ...): ...
    def query_router(self, router: Any, task: Any, args: Any, kwargs: Any, options: Any, task_type: Any): ...

def prepare(routes: Any): ...
