from celery import bootsteps
from typing import Any

class Agent(bootsteps.StartStopStep):
    conditional: bool = ...
    requires: Any = ...
    agent_cls: Any = ...
    def __init__(self, c: Any, **kwargs: Any) -> None: ...
    def create(self, c: Any): ...
