from celery import bootsteps
from typing import Any

class Connection(bootsteps.StartStopStep):
    def __init__(self, c: Any, **kwargs: Any) -> None: ...
    def start(self, c: Any) -> None: ...
    def shutdown(self, c: Any) -> None: ...
    def info(self, c: Any): ...
