from celery import bootsteps
from typing import Any

class Events(bootsteps.StartStopStep):
    requires: Any = ...
    groups: Any = ...
    send_events: Any = ...
    enabled: Any = ...
    def __init__(self, c: Any, task_events: bool = ..., without_heartbeat: bool = ..., without_gossip: bool = ..., **kwargs: Any) -> None: ...
    def start(self, c: Any) -> None: ...
    def stop(self, c: Any) -> None: ...
    def shutdown(self, c: Any) -> None: ...
