from celery import bootsteps
from typing import Any, Optional

class Heart(bootsteps.StartStopStep):
    requires: Any = ...
    enabled: Any = ...
    heartbeat_interval: Any = ...
    def __init__(self, c: Any, without_heartbeat: bool = ..., heartbeat_interval: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def start(self, c: Any) -> None: ...
    def stop(self, c: Any) -> None: ...
    shutdown: Any = ...
