from celery import bootsteps
from typing import Any, Optional

class Mingle(bootsteps.StartStopStep):
    label: str = ...
    requires: Any = ...
    compatible_transports: Any = ...
    enabled: Any = ...
    def __init__(self, c: Any, without_mingle: bool = ..., **kwargs: Any) -> None: ...
    def compatible_transport(self, app: Any): ...
    def start(self, c: Any) -> None: ...
    def sync(self, c: Any) -> None: ...
    def send_hello(self, c: Any): ...
    def on_node_reply(self, c: Any, nodename: Any, reply: Any) -> None: ...
    def sync_with_node(self, c: Any, clock: Optional[Any] = ..., revoked: Optional[Any] = ..., **kwargs: Any) -> None: ...
    def on_clock_event(self, c: Any, clock: Any) -> None: ...
    def on_revoked_received(self, c: Any, revoked: Any) -> None: ...
