from celery import bootsteps
from typing import Any

class Tasks(bootsteps.StartStopStep):
    requires: Any = ...
    def __init__(self, c: Any, **kwargs: Any) -> None: ...
    def start(self, c: Any): ...
    def stop(self, c: Any) -> None: ...
    def shutdown(self, c: Any) -> None: ...
    def info(self, c: Any): ...
