from typing import Any

def fixup(app: Any, env: str = ...): ...

class DjangoFixup:
    app: Any = ...
    def __init__(self, app: Any) -> None: ...
    def install(self): ...
    @property
    def worker_fixup(self): ...
    @worker_fixup.setter
    def worker_fixup(self, value: Any) -> None: ...
    def on_import_modules(self, **kwargs: Any) -> None: ...
    def on_worker_init(self, **kwargs: Any) -> None: ...
    def now(self, utc: bool = ...): ...
    def autodiscover_tasks(self): ...

class DjangoWorkerFixup:
    app: Any = ...
    db_reuse_max: Any = ...
    interface_errors: Any = ...
    DatabaseError: Any = ...
    def __init__(self, app: Any) -> None: ...
    def django_setup(self) -> None: ...
    def validate_models(self) -> None: ...
    def install(self): ...
    def on_worker_process_init(self, **kwargs: Any) -> None: ...
    def on_task_prerun(self, sender: Any, **kwargs: Any) -> None: ...
    def on_task_postrun(self, sender: Any, **kwargs: Any) -> None: ...
    def close_database(self, **kwargs: Any): ...
    def close_cache(self) -> None: ...
    def on_worker_ready(self, **kwargs: Any) -> None: ...
